import = ["/home/yenonn/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[env]
LANG = "en_US.UTF-8"
LC_CTYPE = "en_US.UTF-8"
TERM = "alacritty"

[font]
size = 10

[font.bold]
family = "JetBrains Mono NL"
style = "Bold"

[font.italic]
family = "JetBrains Mono NL"
style = "italic"

[font.normal]
family = "JetBrains Mono NL"
style = "Bold"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Super"

[shell]
program = "/usr/bin/tmux"

[window]
dynamic_title = true
opacity = 1.0
startup_mode = "FullScreen"

[window.dimensions]
columns = 133
lines = 60
